services:
  mongo:
    image: mongo:6
    container_name: image-viewer-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  node-api:
    build:
      context: ./node-api
      dockerfile: Dockerfile.api
    container_name: image-viewer-node-api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/image-viewer-db
      - VITE_API_URL=http://node-api:5000
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: image-viewer-frontend
    ports:
      - "5173:5173"
    depends_on:
      - node-api

volumes:
  mongo_data:

